version: '3.3'

services:
  postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=controlegastos
    ports:
      - "5432:5432"
    volumes:
      - /home/tria/ProjetosPessoais/sistema_controle_gastos_mensais/backend/docker/data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network-bd

networks: 
  postgres-compose-network-bd:
    driver: bridge
