version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/tria/ProjetosPessoais/sistema_controle_gastos_mensais/backend/docker/data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
